### ISSUE TITLE
StructBlock with translatable label crashes in 2.13rc1

### ISSUE THREAD

**Issue by Stormheg** [wagtail/wagtail#7074]
### Issue Summary

I've tried upgrading a staging site to Wagtail 2.13rc1. Unfortunately it broke the page editor. Both for new and existing pages.

The editor remains empty and crashes with the following javascript error:

>Uncaught TypeError: t.replace is not a function
    at Object.e.escapeHtml (text.ts:7)
    at StreamBlock.js:112
    at Array.forEach (<anonymous>)
    at StreamBlock.js:111
    at Array.forEach (<anonymous>)
    at e.renderMenu (StreamBlock.js:103)
    at e.open (StreamBlock.js:160)
    at e.setState (StreamBlock.js:310)
    at new e (StreamBlock.js:210)
    at t.render (StreamBlock.js:359)

My site is using a StructBlock with a translatable label like this:

```python
from wagtail.core import blocks
from django.utils.translation import gettext_lazy as _

class HeaderBlock(blocks.StructBlock):
    title = blocks.CharBlock(label="Title")
    text = blocks.TextBlock(label="Text")

    class Meta:
        # This worked before in 2.12.4.
        # Changing this to just "Header" (without the call to gettext_lazy) works in 2.13rc1
        label = _("Header")

```

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. Edit models.py as follows...

```python
from django.db import models
from django.utils.translation import gettext_lazy as _

from wagtail.core.models import Page
from wagtail.core.fields import StreamField
from wagtail.admin.edit_handlers import StreamFieldPanel

from wagtail.core import blocks

class HeaderBlock(blocks.StructBlock):
    title = blocks.CharBlock(label=_("Title"))
    text = blocks.TextBlock(label=_("Text"))

    class Meta:
        label = _("Header")

class HomePage(Page):
    content = StreamField([
        ("header", HeaderBlock())
    ])

    content_panels = Page.content_panels + [
        StreamFieldPanel("content")
    ]
```
4. Migrate and try editing the home page in the Wagtail admin.
5. You should see the editor remains empty
![image](https://user-images.githubusercontent.com/13856515/115689065-04eea700-a35c-11eb-9e9c-f31df6d35250.png)

My StructBlock isn't very exotic. I would expect it to continue working with translatable labels without any code changes.

I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

* Python version: 3.9.4
* Django version: 3.2
* Wagtail version: 2.13rc1
* Browser version: Chrome 90

**Comment by Stormheg** [comment]
Probably related: https://github.com/wagtail/wagtail/issues/7059

**Comment by gasman** [comment]
Fixed in https://github.com/wagtail/telepath/pull/1 and version-bumped in a006caac94e74e77eb037775748d53efa39d38ce (main) and d041b156b86c1832940556ab226e677e79fe81a6 (stable/2.13.x).

**Comment by Stormheg** [comment]
Awesome! - thank you for fixing @gasman
