### PR TITLE
Fix ImageBlock alt text prefilling logic after EventTarget migration

### LINKED ISSUE #13275: TypeError with EventEmitter to EventTarget 'on' API
### Issue Summary

In Wagtail 7.1rc1, getting a `TypeError: o.on is not a function` in `image-block.js`, that looks like a regression from #13214? It seems those `.on` event listener methods are coming from jQuery, EventEmitter, and other libraries, so we might be missing a few switches from that to `.addEventListener`. Code:

https://github.com/wagtail/wagtail/blob/d1a842f684ab1411bb811640cfa8aec02644680b/client/src/entrypoints/images/image-block.js#L20

### Steps to Reproduce

1. Go to a bakery demo recipe page
2. Add a new image block
3. See browser console

### Technical details

Wagtail 7.1rc1

### Working on this

This will likely require a quick turnaround so I would only recommend this task for people experienced with Wagtail’s client-side code.

### PR DESCRIPTION
**Pull request by laymonage**
Fixes #13275. I've also double-checked the events dispatched by the classes migrated to `EventTarget` to see if there are any remaining `.on(...)` and incorrect `Event()` with data, and couldn't find any.

https://github.com/user-attachments/assets/b4b83653-7f9a-4a23-a903-5f42afae4a25

### CODE REVIEW

**Review by thibaudcolas — APPROVED** [review]
Thank you!
