### ISSUE TITLE
Version 6.3 documentation builds fail with SubqueryConstraint import

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#13013]
### Issue Summary

Our v6.3 documentation builds in Read the Docs are [currently failing](https://app.readthedocs.org/projects/wagtail/builds/27735827/) since the release of Django 5.2, with the following error:

```
ImportError: cannot import name 'SubqueryConstraint' from 'django.db.models.sql.where'
```

### Steps to Reproduce

Do a branch build or tag build in from the `stable/6.3.x` branch.

### Working on this

I assume this is the same issue as was fixed as part of #12880 / https://github.com/wagtail/wagtail/commit/aa7b1d58ef31e1454075351e02d8d714ead0a1be. Since we don’t use lockfiles for our Read the Docs builds, pip installs any Django version meeting `Django>=4.2,<6.0` per our setup.py requires.

I see three possible fixes, not sure which is best:

- Backport that fix to the branch
- Or re-add the upper bound on <5.2 to the 6.3 branch
- ??? possibly find a way to lock our versions installed in Read the Docs specifically

**Comment by gasman** [comment]
Fixed by backporting Django 5.2 fixes to stable/6.3.x (#13030).
