### ISSUE TITLE
Django 4.0+ compatibility

### ISSUE THREAD

**Issue by Salomanuel** [wagtail/wagtail#8091]
as soon as I add to `base.py` this:
```
INSTALLED_APPS += [
   'debug_toolbar',
]
```
I get `ImportError: cannot import name 'url' from 'django.conf.urls'`

apparently `django.conf.urls.url()` was deprecated in Django 3.0, and is removed in Django 4.0+    

is there any way to make Django Debug Toolbar (and many other things that use the same structure) work in Django 4.0+?

**Comment by gasman** [comment]
Hi @Salomanuel,
This is not a Wagtail issue. However, it appears that django-debug-toolbar [updated its urlconfs from `url` to `path`](https://github.com/jazzband/django-debug-toolbar/commit/47d6b5e9d607a5905a2ed668674bafa9dcb0644f) in 3.0, so you probably just need to upgrade it.

**Comment by Salomanuel** [comment]
I'm very sorry, being new to Python and Wagtail I was following a tutorial (wagtail-for-beginners) and it was forcing  `django-debug-toolbar==2.1`
once I changed it to a current version, the problem got fixed

Sorry again for wasting your time!
