### ISSUE TITLE
create_log_entries_from_revisions crashes if previous_revision is not None, but current_revision_as_page is None

### ISSUE THREAD

**Issue by kristinriebe** [wagtail/wagtail#6498]
### Issue Summary

After upgrading to 2.10.2, I tried the new management command create_log_entries_from_revisions on my development instance of Wagtail, which crashed with following error:

```
$ python manage.py create_log_entries_from_revisions

Traceback (most recent call last):
  File "manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/lib/python3.6/site-packages/wagtail/core/management/commands/create_log_entries_from_revisions.py", line 62, in handle
    if current_revision_as_page.live_revision_id == previous_revision.id:
AttributeError: 'NoneType' object has no attribute 'live_revision_id'

```

I didn't have this issue on my production server, so it's possible this only happens when weird circumstances come together.  
In my case, it is actually the line `previous_revision_as_page = previous_revision.as_page_object()` (line 35 in create_log_entries_from_revisions.py) that fails for the page in question with `ValueError: invalid literal for int() with base 10: '2019-01-01'`, but this exception is caught and `previous_revision_as_page` is set to None.  
Therefore it happens that `previous_revision` is not None, but `current_revision_as_page` is None which leads to the error above.

### Workaround

I 'solved' the issue for me on my development instance by temporarily changing the code in `wagtail/core/management/commands/create_log_entries_from_revisions.py`, line 62 to:

```python
if current_revision_as_page is not None:
    if current_revision_as_page.live_revision_id == previous_revision.id:   # fails, if current_revistion_as_page is None
```

### Technical details

* Python version: 3.6.7
* Django version: 2.2.9
* Wagtail version: 2.10.2
