### ISSUE TITLE
'Cast' object has no attribute 'split' when calling render_html() on PagesForModerationPanel object

### ISSUE THREAD

**Issue by thehaseo** [wagtail/wagtail#10087]
I am currently working on a project using wagtail 3.0.3 along with django 4.0.8, I recently updated wagtail to its 4.0 version, however now when I try to load the admin home.html page the error **'Cast' object has no attribute 'split'** is shown on django DEBUG page. 

Tracking the error I realized it happens when the template tag `{% component panel fallback_render_method=True %}` is used with a PagesForModerationPanel object. With the help of django DEBUG traceback I saw function by function until I reach the function instantiating the class `Cast("pk", output_field=models.CharField())` and after that some other functions from modeltranslation are executed until the error is raised. I'll leave the traceback after the `Cast("pk", output_field=models.CharField())` is invoked inside the function `revisions_for_moderation()` in case it helps for something. Any clue about why may this be happening?

wagtail/models/__init__.py, line 3112, in revisions_for_moderation
```
3107.    only_my_sections = Q(path__startswith=publishable_pages_paths[0])
3108.    for page_path in publishable_pages_paths[1:]:
3109.       only_my_sections = only_my_sections | Q(path__startswith=page_path)
3110.       # return the filtered queryset
3111.       return Revision.page_revisions.submitted().filter(
3112.           object_id__in=Page.objects.filter(only_my_sections).values_list(
3113.               Cast("pk", output_field=models.CharField()), flat=True
3114.            )
3115.        )
```

modeltranslation/manager.py, line 450, in values_list
```
446.    selects_all = not fields
447.    if not fields:
448.        # Emulate original queryset behaviour: get all fields that are not translation fields
449.        fields = self._get_original_fields()
450.    clone = self._values(*fields, prepare=True, selects_all=selects_all)
```

modeltranslation\manager.py, line 419, in _values
```
412.    def _values(self, *original, **kwargs):
413.        selects_all = kwargs.pop('selects_all', False)
414.        if not kwargs.pop('prepare', False):
415.            return super(MultilingualQuerySet, self)._values(*original, **kwargs)
416.        new_fields, translation_fields = append_fallback(self.model, original)
417.        annotation_keys = set(self.query.annotation_select.keys()) if selects_all else set()
418.        new_fields.update(annotation_keys)
419.        clone = super(MultilingualQuerySet, self)._values(*list(new_fields), **kwargs) 
```

django\db\models\query.py, line 943, in _values
```
938.    def _values(self, *fields, **expressions):
939.        clone = self._chain()
940.        if expressions:
941.            clone = clone.annotate(**expressions)
942.        clone._fields = fields
943.        clone.query.set_values(fields) 
```

django\db\models\sql\query.py, line 2425, in set_values
```
2418.            for expr in self.group_by:
2419.                if isinstance(expr, Ref) and expr.refs not in selected:
2420.                    expr = self.annotations[expr.refs]
2421.                group_by.append(expr)
2422.            self.group_by = tuple(group_by)
2423. 
2424.        self.values_select = tuple(field_names)
2425.        self.add_fields(field_names, True) 
```

django\db\models\sql\query.py, line 2108, in add_fields
```
2102.        try:
2103.            cols = []
2104.            for name in field_names:
2105.                # Join promotion note - we must not remove any rows here, so
2106.                # if there is no existing joins, use outer join.
2107.                join_info = self.setup_joins(
2108.                    name.split(LOOKUP_SEP), opts, alias, allow_many=allow_m2m …
2109.                )
```

**Comment by gasman** [comment]
@thehaseo What version of wagtail-modeltranslation are you running?

**Comment by thehaseo** [comment]
Maybe worths mentioning I created a new home.html page inside my app but with the conditional:
```
{% if panel.name != 'pages_for_moderation' %}
    {% component panel fallback_render_method=True %}
{% endif %}
```
and it loads ok but obviously without the **pages_for_moderation** panel. 

Checking for the other pages however I realized the page admin/reports/workflow/ has the same problem, it throws the same error, I'll leave the traceback beginning where the Cast() class is instantiated just in case:

wagtail/admin/views/reports/workflows.py, line 45, in get_editable_page_ids_query
```
38. def get_editable_page_ids_query(request):
39.    pages = UserPagePermissionsProxy(request.user).editable_pages()
40.    # Need to cast the page ids to string because Postgres doesn't support
41.    # implicit type casts when querying on GenericRelations
42.    # https://code.djangoproject.com/ticket/16055
43.    # Once the issue is resolved, we can remove this function
44.    # and change the query to page__in=pages
45.    return pages.values_list(Cast("id", output_field=CharField()), flat=True)
```

modeltranslation/manager.py, line 450, in values_list
```
446.    selects_all = not fields
447.    if not fields:
448.        # Emulate original queryset behaviour: get all fields that are not translation fields
449.        fields = self._get_original_fields()
450.    clone = self._values(*fields, prepare=True, selects_all=selects_all) 
```

modeltranslation/manager.py, line 419, in _values
```
412.    def _values(self, *original, **kwargs):
413.        selects_all = kwargs.pop('selects_all', False)
414.        if not kwargs.pop('prepare', False):
415.            return super(MultilingualQuerySet, self)._values(*original, **kwargs)
416.        new_fields, translation_fields = append_fallback(self.model, original)
417.        annotation_keys = set(self.query.annotation_select.keys()) if selects_all else set()
418.        new_fields.update(annotation_keys)
419.        clone = super(MultilingualQuerySet, self)._values(*list(new_fields), **kwargs) 
```

django/db/models/query.py, line 943, in _values
```
938.    def _values(self, *fields, **expressions):
939.        clone = self._chain()
940.        if expressions:
941.            clone = clone.annotate(**expressions)
942.        clone._fields = fields
943.        clone.query.set_values(fields) 
```

django/db/models/sql/query.py, line 2425, in set_values
```
2418.            for expr in self.group_by:
2419.                if isinstance(expr, Ref) and expr.refs not in selected:
2420.                    expr = self.annotations[expr.refs]
2421.                group_by.append(expr)
2422.            self.group_by = tuple(group_by)
2423. 
2424.        self.values_select = tuple(field_names)
2425.        self.add_fields(field_names, True) 
```

django/db/models/sql/query.py, line 2108, in add_fields

```
2102.        try:
2103.            cols = []
2104.            for name in field_names:
2105.                # Join promotion note - we must not remove any rows here, so
2106.                # if there is no existing joins, use outer join.
2107.                join_info = self.setup_joins(
2108.                    name.split(LOOKUP_SEP), opts, alias, allow_many=allow_m2m
2109.                )
```

**Comment by laymonage** [comment]
I wonder if modeltranslation doesn't like expressions in `values`/`values_list`. Perhaps annotating the `Cast` before using it in `values_list` might work, e.g.

```diff
- Page.objects.filter(only_my_sections).values_list(
-     Cast("pk", output_field=models.CharField()), flat=True
- )
+ Page.objects.filter(only_my_sections).annotate(
+     pk_str=Cast("pk", output_field=models.CharField())
+ ).values_list("pk_str", flat=True)
```

**Comment by thehaseo** [comment]
@laymonage Indeed this solution worked perfectly! I tested changing that piece of code in both functions and now home and workflows pages load fine

wagtail\models\__init__.py
```
def revisions_for_moderation(self):
        """Return a queryset of page revisions awaiting moderation that this user has publish permission on"""

        # Deal with the trivial cases first...
        if not self.user.is_active:
            return Revision.objects.none()
        if self.user.is_superuser:
            return Revision.page_revisions.submitted()

        # get the list of pages for which they have direct publish permission
        # (i.e. they can publish any page within this subtree)
        publishable_pages_paths = (
            self.permissions.filter(permission_type="publish")
            .values_list("page__path", flat=True)
            .distinct()
        )
        if not publishable_pages_paths:
            return Revision.objects.none()

        # compile a filter expression to apply to the Revision.page_revisions.submitted() queryset:
        # return only those pages whose paths start with one of the publishable_pages paths
        only_my_sections = Q(path__startswith=publishable_pages_paths[0])
        for page_path in publishable_pages_paths[1:]:
            only_my_sections = only_my_sections | Q(path__startswith=page_path)
        # return the filtered queryset
        return Revision.page_revisions.submitted().filter(
            object_id__in=Page.objects.filter(only_my_sections).annotate(
                pk_str=Cast("pk", output_field=models.CharField())).values_list("pk_str", flat=True)
        )
```

wagtail\admin\views\reports\workflows.py

```
def get_editable_page_ids_query(request):
    pages = UserPagePermissionsProxy(request.user).editable_pages()
    # Need to cast the page ids to string because Postgres doesn't support
    # implicit type casts when querying on GenericRelations
    # https://code.djangoproject.com/ticket/16055
    # Once the issue is resolved, we can remove this function
    # and change the query to page__in=pages
    return pages.annotate(id_str=Cast("id", output_field=CharField())).values_list("id_str", flat=True)
```

**Comment by laymonage** [comment]
This was the issue:

https://github.com/deschler/django-modeltranslation/issues/670

Looks like it's been fixed and the latest version (0.18.9) released last week includes the fix. I think `wagtail-modeltranslation` doesn't enforce an upper boundary for `django-modeltranslation`, so try upgrading your `django-modeltranslation` package to that version.

I'm not sure if this is something that we should handle on our side, given that using expressions in `values`/`values_list()` is valid in Django. Closing as wontfix for now, but feel free to discuss if anyone feels we should add the annotation prior to `values_list()`.
