### ISSUE TITLE
StreamField - adding Blocks that are split inside rich text fields do not work

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail#9911]
### Issue Summary

Splitting blocks from inside a Rich Text block is not working on the current master branch.

### Steps to Reproduce

1. Open up the bakery demo and edit any blog page
2. Attempt to split a rich text block with either the '+' button or by typing `/` and selecting a new block
3. Expected: Blocks get added between two rich text blocks
4. Actual: Nothing happens and console error

```
Uncaught TypeError: window.draftail.DraftUtils.removeCommandPalettePrompt is not a function
    onSelect widgets.js:163
    onSelect draftail.esm.js:1340
    onMouseDown draftail.esm.js:1206
```

![Screen Shot 2023-01-18 at 8 56 48 pm](https://user-images.githubusercontent.com/1396140/213171650-98f99662-bedf-452b-8a62-d9f67a60e52f.png)

![Screen Shot 2023-01-18 at 8 55 32 pm](https://user-images.githubusercontent.com/1396140/213171682-74724ffc-f752-45fc-97e5-bcbcc47f8c50.png)

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (no)

### Technical details

-   Python version: 3.9
-   Wagtail version: 4.2a
-   Browser version: Chrome 109 & Firefox 108 both have the error

### Additional context

* Looks like the file in question changed with https://github.com/wagtail/wagtail/pull/9905
* client/src/entrypoints/admin/telepath/widgets.js
* https://github.com/wagtail/wagtail/blob/main/client/src/entrypoints/admin/telepath/widgets.js#L201

**Comment by lb-** [comment]
@thibaudcolas  - @Lovelyfin00 and I found this when walking through the functionality of StreamFields, I think this somehow got introduced with https://github.com/wagtail/wagtail/pull/9905 but not 100% sure (just tracking git changes).

**Comment by laymonage** [comment]
Have you re-run `npm ci`? Draftail was updated to RC5, which introduced the function.

**Comment by lb-** [comment]
Good call @laymonage  - I thought I had but will try again.

**Comment by lb-** [comment]
Yep - that was it. Thanks!
