### ISSUE TITLE
Wagtail Validation for Blocks

### ISSUE THREAD

**Issue by SteinRobert** [wagtail/wagtail#7202]
There is no documentation on how the validation for blocks works.

### Pertinent section of the Wagtail docs 

https://docs.wagtail.io/en/v2.13/advanced_topics/customisation/streamfield_blocks.html

### Details

I just updated a project to Wagtail 2.13. Having some tests in place which check whether some custom validation logic within the `clean` method of our blocks works we noticed these tests failing.

The tests check whether the error messages actually appear within the wagtail editing interface.

Please consider following example:

```python
    def clean(self, value):
        if bool(value.get("link_text")) != bool(value.get("url")):
            raise ValidationError(
                "ValidationError in DllElementBlock",
                params={
                    "link_text": ErrorList(["Please fill both fields."])
                },
            )
        return super().clean(value)
```

I have a `StructBlock` with a field `url` and a field `link_text`. Both fields need to be either empty or filled.

After the upgrade the error message did not appear.

I changed the validation to the following:

```python
    def clean(self, value):
        if bool(value.get("link_text")) != bool(value.get("url")):
            raise StructBlockValidationError(   # <--- changed exception
                {"link_text": ErrorList(["Please fill both fields."])},
            )
        return super().clean(value)
```

Using `StructBlockValidationError` fixed the issue! The error message is shown.

I would suggest to add some documentation on how to validate blocks and which exceptions to use.

**Comment by mjmare** [comment]
I think validation is not documented for regular fields as well.

**Comment by gasman** [comment]
The current implementation of validation for StructBlock / ListBlock / StreamBlock was not really intended to be used for custom validation in end-user code - it was only designed to deal with propagating errors that occur in FieldBlocks, and there are some design decisions that made sense in that context but are more dubious when the error originates from the StructBlock / ListBlock / StreamBlock itself - e.g. the data of a ListBlock validation error being a list of either `None` or a `ValidationError` instance for each of its child blocks. If we're going to make this a developer-facing API (and I think we should...) then we really need to redesign it to be more user-friendly, rather than document what's already there.

**Comment by nutjob4life** [comment]
Just for context, @KalobTaulien [includes a lesson on StreamField validation](https://learnwagtail.com/wagtail-for-beginners/custom-streamfield-block-validation/) affected by this 😌

**Comment by enzedonline** [comment]
> Just for context, @KalobTaulien [includes a lesson on StreamField validation](https://learnwagtail.com/wagtail-for-beginners/custom-streamfield-block-validation/) affected by this 😌

That lesson is for an old version of Wagtail, the code used will no longer show the errors on the stream blocks.

It needs updating to :

```
from wagtail.blocks.struct_block import StructBlockValidationError
.....

    def clean(self, value):
        errors = {}
        internal_page = value.get('internal_page')
        url_link = value.get('url_link')

        if not(bool(internal_page) ^ bool(url_link)):
            errors['internal_page'] = ErrorList([_("Please select an internal page or an external link (but not both)")])
            errors['url_link'] = ErrorList([_("Please select an internal page or an external link (but not both)")])

        if errors:
            raise StructBlockValidationError(block_errors=errors)

        return super().clean(value)
```

**Comment by minusf** [comment]
after upgrading from 2.16 to 3.0.3 this validation error is not publicly exported anymore and raises an import error:

```
ImportError: cannot import name 'StructBlockValidationError' from 'wagtail.blocks'
```

`struct_block.py`:

```
__all__ = ["BaseStructBlock", "StructBlock", "StructValue"]


class StructBlockValidationError(ValidationError):
    def __init__(self, block_errors=None):
        self.block_errors = block_errors
        super().__init__("Validation error in StructBlock", params=block_errors)
```

**Comment by gasman** [comment]
@minusf `from wagtail.blocks.struct_block import StructBlockValidationError` works for me on current main. Importing from `wagtail.blocks` (or `wagtail.core.blocks`) would never have worked, because the `__all__` line has always been there.

**Comment by minusf** [comment]
thank you, indeed i went back in history and the `__all__` line was always the same.

the confusing part form is i guess also the intention (`__all__`) not to have it "public".
thank you for providing the model path diffing tool, helps quite a bit.

**Comment by JeremyGibson** [comment]
Just food for thought as you proceed with your excellent work and perhaps add a public api for these errors. I noticed during testing code that uses `StructBlockValidationError` that although the cms admin displays the errors in the correct place and with the correct message, the error messages are getting lost somewhere in the process of automated testing. AFAIK this also happens using django testing framework, but I haven't tested it yet.

Wagtail == 4.1
Django == 4.0
Pytest == 6.2.5

**The Clean**
```python
    def clean(self, value):
        value = super().clean(value)
        errors = {}
        if not [x for x in value.bound_blocks.values() if x.value]:
            errors["document"] = ErrorList([_("A Format must be chosen.")])
            errors["page"] = ErrorList([_("A Format must be chosen.")])
            raise StructBlockValidationError(block_errors=errors)
        return value
```

**The Test**
```python
def test_no_formats():
    block = blocks.ResourceBlock()
    rb = _resource_block()
    rb["topic"] = rb["topic"].pk
    rb["type"] = rb["type"].pk
    rb["resource_format"] = {}
    with pytest.raises(ValidationError) as excinfo:
        block.clean(block.to_python(rb))
    assert excinfo.value.message == "Validation error in StructBlock"
```

**Comment by gasman** [comment]
The validation mechanism has been simplified for better developer-friendliness (see https://github.com/wagtail/wagtail/issues/7250#issuecomment-1434737846), and documented in #10165.
