### ISSUE TITLE
Attribute Error on TitleFieldPanel with read_only=True

### ISSUE THREAD

**Issue by lasse-cs** [wagtail/wagtail#13212]
### Issue Summary

According to the Wagtail documentation, the `TitleFieldPanel` supports all the arguments of the parent `FieldPanel`. https://docs.wagtail.org/en/stable/reference/panels.html#titlefieldpanel

However, trying to edit a page with a `TitleFieldPanel` that has `read_only` set to true raises an `AttributeError`:

>   File "/home/user/django_projects/wagtail/check_read_only/.venv/lib/python3.11/site-packages/wagtail/admin/panels/title_field_panel.py", line 57, in get_context_data
    field = self.bound_field.field
            ^^^^^^^^^^^^^^^^^^^^^^
>
> Exception Type: AttributeError at /admin/pages/3/edit/
> Exception Value: 'NoneType' object has no attribute 'field'

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2.  Edit the `home/models.py` as follows:  
  ```python
from wagtail.models import Page
from wagtail.admin.panels import TitleFieldPanel


class HomePage(Page):
      content_panels = [
          TitleFieldPanel("title", read_only=True)
    ]
```
3. Migrate, create a super user and try to edit or create a `HomePage` model.

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

-   Python version: Python 3.11.11.
-   Django version: 5.2.4.
-   Wagtail version: 7.0.1

### Working on this

I would be happy to try and work on this if accepted.

My thought is that it might be sufficient to replace the `get_context_data` method of the `TitleFieldPanel.BoundPanel` class with `get_editable_context_data`.
https://github.com/wagtail/wagtail/blob/80f205d61fc16286be892d7bb66fcd0a72842a13/wagtail/admin/panels/title_field_panel.py#L56-L60

I guess this would become something like 
```python
def get_editable_context_data(self):
    field = self.bound_field.field
    if field:
        field.widget.attrs.update(**self.get_attrs())
    return super().get_editable_context_data()
```

Anyone can contribute to this. View our [contributing guidelines](https://docs.wagtail.org/en/latest/contributing/index.html), add a comment to the issue once you’re ready to start.

**Comment by Sumit1797** [comment]
I can work on this

**Comment by thibaudcolas** [comment]
Thank you @Sumit1797, first step will be to attempt to reproduce the issue and share your findings here.

**Comment by Sumit1797** [comment]
**Reproduction**

Followed the steps above and was clearly able to see the issue.

**Findings**
I may be wrong, open for suggestions on this,

The problem what i could see is in the __init__ function of FieldPanel.BoundPanel as can be seen in the location of error here 

<img width="1736" height="363" alt="Image" src="https://github.com/user-attachments/assets/ab47ddbb-2964-451c-9ba7-f9dafee559fc" />

The object is throwing an exception as it is None, which is set in __init__ and only then referenced in the get_context_function.

**Working on the solution**

I am still trying to understand the solution as  i am not sure how to check dynamic values using logs here. It will still more look like in the direction of proper initialization of bound_field with TitleFieldPanel. But nevertheless I will update soon.

**Comment by blu14x** [comment]
+1 this does not only apply to the TitleFieldPanel

**Comment by tombreit** [comment]
Same here: also on on `FieldPanel`. The tests in wagtail==7.1 will fail with setting a `FieldPanel(fieldname, read_only=True)`:

```patch
diff --git a/wagtail/test/testapp/models.py b/wagtail/test/testapp/models.py
index b8a1014dc1..82ca1187ed 100644
--- a/wagtail/test/testapp/models.py
+++ b/wagtail/test/testapp/models.py
@@ -619,7 +619,7 @@ class FormPage(AbstractEmailForm):
             [
                 FieldPanel("to_address"),
                 FieldPanel("from_address"),
-                FieldPanel("subject"),
+                FieldPanel("subject", read_only=True),
             ],
             "Email",
         ),
```

Results in:

```
======================================================================
ERROR: test_post_edit_form (wagtail.contrib.forms.tests.test_views.TestFormPageEdit.test_post_edit_form)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/wagtail/.venv/lib/python3.13/site-packages/telepath/__init__.py", line 318, in build_node
    existing_node = self.nodes[obj_id]
                    ~~~~~~~~~~^^^^^^^^
KeyError: 140696131635872

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/build/wagtail/.venv/lib/python3.13/site-packages/telepath/__init__.py", line 318, in build_node
    existing_node = self.nodes[obj_id]
                    ~~~~~~~~~~^^^^^^^^
KeyError: 140696133638272

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/build/wagtail/.venv/lib/python3.13/site-packages/telepath/__init__.py", line 318, in build_node
    existing_node = self.nodes[obj_id]
                    ~~~~~~~~~~^^^^^^^^
KeyError: 140696125597952

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/build/wagtail/.venv/lib/python3.13/site-packages/telepath/__init__.py", line 318, in build_node
    existing_node = self.nodes[obj_id]
                    ~~~~~~~~~~^^^^^^^^
KeyError: 140696125932720

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/build/wagtail/.venv/lib/python3.13/site-packages/telepath/__init__.py", line 318, in build_node
    existing_node = self.nodes[obj_id]
                    ~~~~~~~~~~^^^^^^^^
KeyError: 140696122825280

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/build/wagtail/.venv/lib/python3.13/site-packages/telepath/__init__.py", line 318, in build_node
    existing_node = self.nodes[obj_id]
                    ~~~~~~~~~~^^^^^^^^
KeyError: 140696138069376

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/build/wagtail/.venv/lib/python3.13/site-packages/telepath/__init__.py", line 318, in build_node
    existing_node = self.nodes[obj_id]
                    ~~~~~~~~~~^^^^^^^^
KeyError: 140696125945040

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/build/wagtail/.venv/lib/python3.13/site-packages/telepath/__init__.py", line 318, in build_node
    existing_node = self.nodes[obj_id]
                    ~~~~~~~~~~^^^^^^^^
KeyError: 140696139383424

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/build/wagtail/.venv/lib/python3.13/site-packages/telepath/__init__.py", line 318, in build_node
    existing_node = self.nodes[obj_id]
                    ~~~~~~~~~~^^^^^^^^
KeyError: 140696138059456

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/build/wagtail/.venv/lib/python3.13/site-packages/telepath/__init__.py", line 318, in build_node
    existing_node = self.nodes[obj_id]
                    ~~~~~~~~~~^^^^^^^^
KeyError: 140696125504752

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/build/wagtail/wagtail/contrib/forms/tests/test_views.py", line 2380, in test_post_edit_form
    self.assertRedirects(
    ~~~~~~~~~~~~~~~~~~~~^
        response, reverse("wagtailadmin_pages:edit", args=(self.form_page.id,))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/build/wagtail/.venv/lib/python3.13/site-packages/django/test/testcases.py", line 519, in assertRedirects
    redirect_response = response.client.get(
        path,
    ...<3 lines>...
        **extra,
    )
  File "/build/wagtail/.venv/lib/python3.13/site-packages/django/test/client.py", line 1124, in get
    response = super().get(
        path,
    ...<4 lines>...
        **extra,
    )
  File "/build/wagtail/.venv/lib/python3.13/site-packages/django/test/client.py", line 475, in get
    return self.generic(
           ~~~~~~~~~~~~^
        "GET",
        ^^^^^^
    ...<4 lines>...
        **extra,
        ^^^^^^^^
    )
    ^
  File "/build/wagtail/.venv/lib/python3.13/site-packages/django/test/client.py", line 671, in generic
    return self.request(**r)
           ~~~~~~~~~~~~^^^^^
  File "/build/wagtail/.venv/lib/python3.13/site-packages/django/test/client.py", line 1087, in request
    self.check_exception(response)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/build/wagtail/.venv/lib/python3.13/site-packages/django/test/client.py", line 802, in check_exception
    raise exc_value
  File "/build/wagtail/.venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/build/wagtail/.venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/build/wagtail/.venv/lib/python3.13/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/build/wagtail/wagtail/admin/urls/__init__.py", line 178, in wrapper
    return view_func(request, *args, **kwargs)
  File "/build/wagtail/wagtail/admin/auth.py", line 137, in decorated_view
    return get_localized_response(view_func, request, *args, **kwargs)
  File "/build/wagtail/wagtail/admin/localization.py", line 138, in get_localized_response
    response = view_func(request, *args, **kwargs)
  File "/build/wagtail/.venv/lib/python3.13/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/wagtail/wagtail/admin/views/pages/edit.py", line 409, in dispatch
    return super().dispatch(request, page_id, **kwargs)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/wagtail/.venv/lib/python3.13/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
  File "/build/wagtail/wagtail/admin/views/pages/edit.py", line 454, in get
    return self.render_to_response(self.get_context_data())
                                   ~~~~~~~~~~~~~~~~~~~~~^^
  File "/build/wagtail/wagtail/admin/views/pages/edit.py", line 950, in get_context_data
    edit_handler_data = js_context.pack(bound_panel)
  File "/build/wagtail/.venv/lib/python3.13/site-packages/telepath/__init__.py", line 220, in pack
    return ValueContext(self).build_node(obj).emit()
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/build/wagtail/.venv/lib/python3.13/site-packages/telepath/__init__.py", line 321, in build_node
    node = self._build_new_node(val)
  File "/build/wagtail/.venv/lib/python3.13/site-packages/telepath/__init__.py", line 339, in _build_new_node
    return adapter.build_node(obj, self)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/build/wagtail/.venv/lib/python3.13/site-packages/telepath/__init__.py", line 169, in build_node
    constructor, [context.build_node(arg) for arg in args]
                  ~~~~~~~~~~~~~~~~~~^^^^^
  File "/build/wagtail/.venv/lib/python3.13/site-packages/telepath/__init__.py", line 321, in build_node
    node = self._build_new_node(val)
  File "/build/wagtail/.venv/lib/python3.13/site-packages/telepath/__init__.py", line 339, in _build_new_node
    return adapter.build_node(obj, self)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/build/wagtail/.venv/lib/python3.13/site-packages/telepath/__init__.py", line 142, in build_node
    str(key): context.build_node(val)
              ~~~~~~~~~~~~~~~~~~^^^^^
  File "/build/wagtail/.venv/lib/python3.13/site-packages/telepath/__init__.py", line 321, in build_node
    node = self._build_new_node(val)
  File "/build/wagtail/.venv/lib/python3.13/site-packages/telepath/__init__.py", line 354, in _build_new_node
    return ListNode([self.build_node(item) for item in items])
                     ~~~~~~~~~~~~~~~^^^^^^
  File "/build/wagtail/.venv/lib/python3.13/site-packages/telepath/__init__.py", line 321, in build_node
    node = self._build_new_node(val)
  File "/build/wagtail/.venv/lib/python3.13/site-packages/telepath/__init__.py", line 339, in _build_new_node
    return adapter.build_node(obj, self)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/build/wagtail/.venv/lib/python3.13/site-packages/telepath/__init__.py", line 169, in build_node
    constructor, [context.build_node(arg) for arg in args]
                  ~~~~~~~~~~~~~~~~~~^^^^^
  File "/build/wagtail/.venv/lib/python3.13/site-packages/telepath/__init__.py", line 321, in build_node
    node = self._build_new_node(val)
  File "/build/wagtail/.venv/lib/python3.13/site-packages/telepath/__init__.py", line 339, in _build_new_node
    return adapter.build_node(obj, self)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/build/wagtail/.venv/lib/python3.13/site-packages/telepath/__init__.py", line 142, in build_node
    str(key): context.build_node(val)
              ~~~~~~~~~~~~~~~~~~^^^^^
  File "/build/wagtail/.venv/lib/python3.13/site-packages/telepath/__init__.py", line 321, in build_node
    node = self._build_new_node(val)
  File "/build/wagtail/.venv/lib/python3.13/site-packages/telepath/__init__.py", line 354, in _build_new_node
    return ListNode([self.build_node(item) for item in items])
                     ~~~~~~~~~~~~~~~^^^^^^
  File "/build/wagtail/.venv/lib/python3.13/site-packages/telepath/__init__.py", line 321, in build_node
    node = self._build_new_node(val)
  File "/build/wagtail/.venv/lib/python3.13/site-packages/telepath/__init__.py", line 339, in _build_new_node
    return adapter.build_node(obj, self)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/build/wagtail/.venv/lib/python3.13/site-packages/telepath/__init__.py", line 169, in build_node
    constructor, [context.build_node(arg) for arg in args]
                  ~~~~~~~~~~~~~~~~~~^^^^^
  File "/build/wagtail/.venv/lib/python3.13/site-packages/telepath/__init__.py", line 321, in build_node
    node = self._build_new_node(val)
  File "/build/wagtail/.venv/lib/python3.13/site-packages/telepath/__init__.py", line 339, in _build_new_node
    return adapter.build_node(obj, self)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/build/wagtail/.venv/lib/python3.13/site-packages/telepath/__init__.py", line 142, in build_node
    str(key): context.build_node(val)
              ~~~~~~~~~~~~~~~~~~^^^^^
  File "/build/wagtail/.venv/lib/python3.13/site-packages/telepath/__init__.py", line 321, in build_node
    node = self._build_new_node(val)
  File "/build/wagtail/.venv/lib/python3.13/site-packages/telepath/__init__.py", line 354, in _build_new_node
    return ListNode([self.build_node(item) for item in items])
                     ~~~~~~~~~~~~~~~^^^^^^
  File "/build/wagtail/.venv/lib/python3.13/site-packages/telepath/__init__.py", line 321, in build_node
    node = self._build_new_node(val)
  File "/build/wagtail/.venv/lib/python3.13/site-packages/telepath/__init__.py", line 339, in _build_new_node
    return adapter.build_node(obj, self)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/build/wagtail/.venv/lib/python3.13/site-packages/telepath/__init__.py", line 167, in build_node
    constructor, args = self.pack(obj, context)
                        ~~~~~~~~~^^^^^^^^^^^^^^
  File "/build/wagtail/.venv/lib/python3.13/site-packages/telepath/__init__.py", line 178, in pack
    return obj.telepath_pack(context)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/build/wagtail/wagtail/admin/panels/base.py", line 339, in telepath_pack
    return (self.telepath_adapter_name, [self.js_opts()])
                                         ~~~~~~~~~~~~^^
  File "/build/wagtail/wagtail/admin/panels/field_panel.py", line 404, in js_opts
    "widget": self.bound_field.field.widget,
              ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'field'

----------------------------------------------------------------------
Ran 83 tests in 4.485s

FAILED (errors=8)
```

**Comment by jerivas** [comment]
Can confirm, the regular `FieldPanel` is also broken when `read_only=True`. This only happens in Wagtail 7.1

**Comment by lasse-cs** [comment]
It looks like this is perhaps a separate issue with the `FieldPanel` in Wagtail 7.1.

I think this was perhaps first introduced in #13248 (perhaps first in https://github.com/wagtail/wagtail/pull/13248/commits/7b2cfaecc790dae508c4e7637799b80cdc92bd77), the `bound_field` attribute will be `None` if the `FieldPanel` is `read_only`, which then causes issues later when it is accessed in the `js_opts` method.

A test to reproduce might be something like

```python
# wagtail/test/testapp/models.py
class ReadOnlyPage(Page):
    subtitle = models.CharField(max_length=255, blank=True)

    content_panels = Page.content_panels + [FieldPanel("subtitle", read_only=True)]

# wagtail/tests/test_read_only_field.py
class TestReadOnlyField(WagtailPageTestCase):

    def setUp(self):
        super().setUp()
        root = Page.get_first_root_node()
        self.read_only_page = ReadonlyField(title="Read Only Page")
        root.add_child(instance=self.read_only_page)

    def test_read_only_field(self):
        self.assertPageIsEditable(self.read_only_page, post_data={
            "title": "Updated Read Only Page",
        })
```

**Comment by anvishinc** [comment]
Just experienced the same issue on Wagtail 7.1 while my Wagtail 7.0.2 project works perfectly fine when I set `read_only=True` on `FieldPanel`.

**Comment by anvishinc** [comment]
Has there been any further development on this?

**Comment by gasman** [comment]
@anvishinc There is no need to ask about updates, especially after only three days - please see https://justinmayer.com/posts/any-updates/ .

**Comment by gasman** [comment]
Fixed (for both FieldPanel and TitleFieldPanel) in #13350 - this will be released as part of Wagtail 7.1.1.
