### PR TITLE
Tests for Allow deep contentpath for comments on fields other than StreamField

### PR DESCRIPTION
**Pull request by lasse-cs**
Build on #12846 to add tests for #12257.

Add tests to check `has_valid_contentpath` on a comment for 
- A valid path in a `StreamField`.
- A valid path in a field that implements `get_block_by_content_path`.
- An invalid path in a field that implements `get_block_by_content_path`.
- A valid path in a field that does not implement `get_block_by_content_path`.

### CODE REVIEW

File: wagtail/tests/test_comments.py [hunk 1]
```diff
@@ -41,3 +43,66 @@ def test_deleting_most_recent_revision_deletes_created_comments(self):
         self.revision_3.delete()
         with self.assertRaises(Comment.DoesNotExist):
             self.new_comment.refresh_from_db()
+
+
+class TestContentPath(WagtailTestUtils, TestCase):
```
Comment (laymonage) [inline wagtail/tests/test_comments.py]: I'm a bit hesitant to have only unit tests specifically for the `has_valid_contentpath()` method instead of on a higher level where it is actually used, particularly because we end up mostly testing the behaviour of `get_block_by_content_path` in the `CommentableJSONField`... which was written specifically for the test (and not a Wagtail feature by itself).

Looking at the history of `has_valid_contentpath()`, it was introduced in #10798 to filter out comments on StreamField blocks that no longer exist. In that PR, `has_valid_contentpath()` is not tested directly, but rather via the following test:

https://github.com/wagtail/wagtail/blob/eaf082966627c17730e88551b8befbe510c384fd/wagtail/admin/tests/pages/test_edit_page.py#L4048-L4051

There are unit tests for `get_block_by_content_path()` in that PR, but that makes sense because it's written as an API of `StreamField`, whereas `CommentableJSONField` exists purely for our testing.

So, I think we should adapt the tests to `TestCommentOutput` instead. I've done this locally as I reviewed the PR, so I'll do this as I merge.

**Review by laymonage — COMMENTED** [review]
Thanks for the PR! Sorry it took me a long time to get to this since the first PR. I wanted to make sure don't end up writing tests for test code. I left a comment for more details.

**Review by laymonage — APPROVED** [review]
Thanks, welcome aboard! 🚢  :shipit:
