### ISSUE TITLE
TypeError with EventEmitter to EventTarget 'on' API

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#13275]
### Issue Summary

In Wagtail 7.1rc1, getting a `TypeError: o.on is not a function` in `image-block.js`, that looks like a regression from #13214? It seems those `.on` event listener methods are coming from jQuery, EventEmitter, and other libraries, so we might be missing a few switches from that to `.addEventListener`. Code:

https://github.com/wagtail/wagtail/blob/d1a842f684ab1411bb811640cfa8aec02644680b/client/src/entrypoints/images/image-block.js#L20

### Steps to Reproduce

1. Go to a bakery demo recipe page
2. Add a new image block
3. See browser console

### Technical details

Wagtail 7.1rc1

### Working on this

This will likely require a quick turnaround so I would only recommend this task for people experienced with Wagtail’s client-side code.
