### ISSUE TITLE
RichText Popups not working in Safari and Firefox

### ISSUE THREAD

**Issue by kaduuuken** [wagtail/wagtail#4078]
When I want to set a link in a RichText Field, the Pop-up doesn't show, instead I get console errors:
`TypeError: rangy.getSelection is not a function. (In 'rangy.getSelection()', 'rangy.getSelection' is undefined)`. This happens in Safari and Firefox, in Chrome it seems to work.

I'm using Django 1.11.7, Python 3.61 and Wagtail 1.13.1

I found that replacing the following in the file `wagtailadmin/templates/wagtailadmin/pages/_editor_js.html` solved the issue:

`<script src="https://unpkg.com/rangy@1.3.0/lib/rangy-core.js"></script>`
instead of
`<script src="{% static 'wagtailadmin/js/vendor/rangy-core.js' %}"></script>`

**Comment by lb-** [comment]
@kaduuuken thank you for this issue submission.

Could you clarify your operating system and browser versions and are you including any other custom JS that may be conflicting somehow (might be a stretch)?

I could not reproduce this issue on macOS 10.12.16 with Safari Version 11.0.1 (12604.3.5.1.1) or Firefox 48.0.2

I also could not see what difference Rangy 1.3.0 would make to the version in use (1.2.3), when looking through the releases: https://github.com/timdown/rangy/releases

In Chrome though, I do get a deprecation warning:
> rangy-core.js:80 [Deprecation] The behavior that Selection.addRange() merges existing Range and the specified Range was removed. See https://www.chromestatus.com/features/6680566019653632 for more details.
This has been reported on Rangy here: https://github.com/timdown/rangy/issues/419

**Comment by kaduuuken** [comment]
I am using macOS 10.12.6 and Safari Version 11.0.1 (12604.3.5.1.1). I just tested again, and right now it seems to work on Chrome Version 50.0.2661.102 (64-bit) and Firefox 57.0 (64-Bit), but still not in Safari.

**Comment by Proper-Job** [comment]
@kaduuuken is this perhaps a browser cache problem?  Have you tried reloading without cache?

**Comment by kaduuuken** [comment]
@Proper-Job I just tried and sadly that does not solve the issue.

**Comment by lb-** [comment]
@kaduuuken just tried on Firefox 57.0 (64-Bit) also and could not reproduce (did not realise how out of date mine was haha). 

I also tested on a live production instance of Wagtail.

Is the issue on your live/production version and your local development version?

**Comment by kaduuuken** [comment]
@lb- It is currently local development version, as soon as the server is set up, I would test it there too, that will probably be today or tomorrow.

**Comment by kaduuuken** [comment]
@lb- I still have the problem on the server, but a colleague of mine checked too in Safari, works fine for him, so I guess it must be a local problem for me...

**Comment by lb-** [comment]
@kaduuuken ok, will close the issue for now.
