### ISSUE TITLE
Preview mode doesn't work under WSGI/Gunicorn

### ISSUE THREAD

**Issue by emorozov** [wagtail/wagtail#3546]
### Issue Summary

Attempt to preview any page results in exception.

### Steps to Reproduce

1. Open any page in the WagTail CMS for editing
2. Click Preview button

Site is running under nginx/gunicorn. When I run Django development server, this problem doesn't happen, preview works as expected. This is clearly related to gunicorn, but when I run local instance of gunicorn, it doesn't happen either. Only on the remote site.

It seems that tricks that Wagtail uses to load preview in a new window causes the problem.

After reading Wagtail source code I found this:
```
        preview_mode = request.GET.get('mode', page.default_preview_mode)
        response = page.serve_preview(page.dummy_request(request), preview_mode)
        response['X-Wagtail-Preview'] = 'ok'
        return response
```
in `wagtail/wagtailadmin/views/pages.py`

Apparently, differences in requests under local django devserver and gunicorn causes some malfunction in the Django authentication middleware and it fails to load currently logged in user while in preview mode.

Since this happens only in WagTail preview and all other views and dependencies functioned perfectly well in this setup for years, I assume this is a Wagtail bug.

I have "fixed" this issue in my case by changing the line from:
`response = page.serve_preview(page.dummy_request(request), preview_mode)`
to:
`response = page.serve_preview(request, preview_mode)`
On line 562 in `wagtail/wagtailadmin/views/pages.py`

I see that master branch uses the same dummy request technique that probably will also fail when running under gunicorn.

### Technical details
```
AttributeError at /cms/pages/29/edit/preview/
'WSGIRequest' object has no attribute 'user'

Request Method: POST
Request URL: https://staging.royalorchard.com/cms/pages/29/edit/preview/
Django Version: 1.10.6
Python Executable: /home/rolc/.virtualenvs/dev/bin/python3
Python Version: 3.5.2
Python Path: ['/home/rolc/dev', '/home/rolc/.virtualenvs/dev/bin', '/home/rolc/.virtualenvs/dev/lib/python35.zip', '/home/rolc/.virtualenvs/dev/lib/python3.5', '/home/rolc/.virtualenvs/dev/lib/python3.5/plat-x86_64-linux-gnu', '/home/rolc/.virtualenvs/dev/lib/python3.5/lib-dynload', '/usr/lib/python3.5', '/usr/lib/python3.5/plat-x86_64-linux-gnu', '/home/rolc/.virtualenvs/dev/lib/python3.5/site-packages']
Server time: Fri, 14 Apr 2017 03:21:22 -0400
Installed Applications:
('django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.messages',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.humanize',
 'django.contrib.staticfiles',
 'django.contrib.admindocs',
 'django.contrib.flatpages',
 'tagging',
 'django_extensions',
 'filebrowser',
 'crispy_forms',
 'floppyforms',
 'allauth',
 'allauth.account',
 'allauth.socialaccount',
 'reversion',
 'papertrail',
 'wagtail.wagtailforms',
 'wagtail.wagtailredirects',
 'wagtail.wagtailembeds',
 'wagtail.wagtailsites',
 'wagtail.wagtailusers',
 'wagtail.wagtailsnippets',
 'wagtail.wagtaildocs',
 'wagtail.wagtailimages',
 'wagtail.wagtailsearch',
 'wagtail.wagtailadmin',
 'wagtail.wagtailcore',
 'wagtail.contrib.table_block',
 'modelcluster',
 'taggit',
 'taggit_templatetags2',
 'royal_orchard.users',
 'royal_orchard.reports',
 'royal_orchard.documents',
 'royal_orchard.emails',
 'royal_orchard.blog',
 'royal_orchard.reservations',
 'royal_orchard.vendors',
 'royal_orchard.flickr',
 'royal_orchard.search',
 'royal_orchard.userpages',
 'tinymce',
 'sorl.thumbnail',
 'constance',
 'constance.backends.database',
 'djmail',
 'bootstrap_pagination')
Installed Middleware:
('django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.contrib.admindocs.middleware.XViewMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'wagtail.wagtailcore.middleware.SiteMiddleware',
 'wagtail.wagtailredirects.middleware.RedirectMiddleware')


Traceback:  

File "/home/rolc/.virtualenvs/dev/lib/python3.5/site-packages/django/core/handlers/exception.py" in inner
  42.             response = get_response(request)

File "/home/rolc/.virtualenvs/dev/lib/python3.5/site-packages/django/core/handlers/base.py" in _legacy_get_response
  249.             response = self._get_response(request)

File "/home/rolc/.virtualenvs/dev/lib/python3.5/site-packages/django/core/handlers/base.py" in _get_response
  217.                 response = self.process_exception_by_middleware(e, request)

File "/home/rolc/.virtualenvs/dev/lib/python3.5/site-packages/django/core/handlers/base.py" in _get_response
  215.                 response = response.render()

File "/home/rolc/.virtualenvs/dev/lib/python3.5/site-packages/django/template/response.py" in render
  109.             self.content = self.rendered_content

File "/home/rolc/.virtualenvs/dev/lib/python3.5/site-packages/django/template/response.py" in rendered_content
  86.         content = template.render(context, self._request)

File "/home/rolc/.virtualenvs/dev/lib/python3.5/site-packages/django/template/backends/django.py" in render
  66.             return self.template.render(context)

File "/home/rolc/.virtualenvs/dev/lib/python3.5/site-packages/django/template/base.py" in render
  206.                 with context.bind_template(self):

File "/usr/lib/python3.5/contextlib.py" in __enter__
  59.             return next(self.gen)

File "/home/rolc/.virtualenvs/dev/lib/python3.5/site-packages/debug_toolbar/panels/templates/panel.py" in _request_context_bind_template
  49.         context = processor(self.request)

File "/home/rolc/dev/royal_orchard/blog/context_processors.py" in context
  10.     user = request.user

Exception Type: AttributeError at /cms/pages/29/edit/preview/
Exception Value: 'WSGIRequest' object has no attribute 'user'
Request information:
USER: Robert ***********

GET: No GET data

POST:
seo_title = ''
expire_at = ''
csrfmiddlewaretoken = '******'
body-0-type = 'paragraph'
body-count = '1'
go_live_at = ''
body-0-deleted = ''
search_description = ''
body-0-order = '0'
slug = '******-history'
title = '****** History'
next = ''
body-0-value = '<p>I feel so very privileged to be invited into your home and if we also feel a little intimidated because we are talking to folks who have generational knowledge of this wonderful house and I know as we do so we are little bit nervous about giving you advice on wh</p>'
```

* Python version: 3.5.2.
* Django version: 1.10.6.
* Wagtail version: 1.9.
* Browser version: Firefox 52.0.2 on Ubuntu Linux.
* Gunicorn: 19.7.1
* Nginx: 1.10.0

**Comment by alexfromvl** [comment]
I use the wagtail 1.9 on the site together with the Gunicorn. The preview_mode works well.

Probably you have a problem in the settings of the Gunicorn or Nginx.

**Comment by emorozov** [comment]
There's nothing unusual in my configuration.
Gunicorn is started with this cmdline:
`/home/rolc/.virtualenvs/dev/bin/gunicorn --pid /run/gunicorn-dev/pid -b unix:/run/gunicorn-dev/socket --reload app.wsgi:application`

Nginx conf is:
```
        if (!-f $request_filename) {
            proxy_pass http://unix:/tmp/gunicorn/socket;
        }
```

No other piece of code or third-party app fails under this configuration, only Wagtail preview. :(

**Comment by alexfromvl** [comment]
You need to look at the mistakes associated with Django. Because the error is in the user "`'WSGIRequest' object has no attribute 'user'`"

https://docs.djangoproject.com/en/dev/ref/middleware/#django.contrib.auth.middleware.SessionAuthenticationMiddleware

**Comment by gasman** [comment]
Looking closely at the stack trace here, I think there might be a different exception being thrown during middleware processing (probably because the dummy request is missing some other property that the middleware depends on) - as a result, it never reaches `AuthenticationMiddleware`, and it's failing with `'WSGIRequest' object has no attribute 'user'` while attempting to render the error page.

Please can you try updating `blog/context_processors.py` so that it doesn't fail in the absence of `request.user`, and see if that gives a more helpful error?

**Comment by emorozov** [comment]
When I modify the context processor to not fail in absence of `request.user`, preview doesn't fail. It seems that `SessionAuthenticationMiddleware` unable to load user when it's using fake request.

**Comment by emorozov** [comment]
I have added debug prints to wagtail and django and here's what I get:
```
Procesing request <WSGIRequest: GET '/cms/pages/29/revisions/4/view/'> with middleware <django.middleware.security.SecurityMiddleware object at 0x7fa625f1cf98>
Procesed
Procesing request <WSGIRequest: GET '/cms/pages/29/revisions/4/view/'> with middleware <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fa625f1cf60>
Procesed
Procesing request <WSGIRequest: GET '/cms/pages/29/revisions/4/view/'> with middleware <django.middleware.common.CommonMiddleware object at 0x7fa625f1cb70>
Procesed
Procesing request <WSGIRequest: GET '/cms/pages/29/revisions/4/view/'> with middleware <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fa625f1c7b8>
Procesed
Procesing request <WSGIRequest: GET '/cms/pages/29/revisions/4/view/'> with middleware <django.contrib.messages.middleware.MessageMiddleware object at 0x7fa625f1c7f0>
Procesed
Procesing request <WSGIRequest: GET '/cms/pages/29/revisions/4/view/'> with middleware <wagtail.wagtailcore.middleware.SiteMiddleware object at 0x7fa626030780>
Procesed
starting processing request <WSGIRequest: GET '/pages/info/milner-history/'>
Procesing request <WSGIRequest: GET '/pages/info/milner-history/'> with middleware <django.middleware.security.SecurityMiddleware object at 0x7fa622b92908>
Procesed
Procesing request <WSGIRequest: GET '/pages/info/milner-history/'> with middleware <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fa622b92898>
Procesed
Procesing request <WSGIRequest: GET '/pages/info/milner-history/'> with middleware <django.middleware.common.CommonMiddleware object at 0x7fa622b92b00>
finished processing request <WSGIRequest: GET '/pages/info/milner-history/'>
```

So it seems, that all middleware is applied to the original request, but only first three entries are applied to the dummy request for some reason. There're no errors during middleware loading and application, so I still can't find the reason why `AuthenticationMiddleware` is never called for dummy request.

**Comment by gasman** [comment]
@emorozov Is it possible that `CommonMiddleware` is returning a (non-error) response? In this situation the rest of the middleware chain is skipped. (For old-style `MIDDLEWARE_CLASSES` definitions, we [explicitly ignored those responses](https://github.com/wagtail/wagtail/blob/18cf4fc5b66d6c5bce04b8406fca07403c166338/wagtail/wagtailcore/models.py#L1207-L1220) and continued with the chain. Perhaps we need to do that with new-style middlewares too...)

**Comment by emorozov** [comment]
@gasman Thank you! Your suggestion was right. I've found the problem: Wagtail uses its own `Site` model which is set to `localhost` by default. Since, on staging/production sites there's no localhost in `settings.ALLOWED_HOSTS`, `CommonMiddleware` were failing and exception message was silently suppressed. So, no session and authentication middleware were run, but exception is lost somewhere, so it was almost impossible to find the real cause of the problem.

I think this is still a bug. It should be either documented somewhere to set proper hostname for the wagtail `Site` (can it take value from Django `Site` which is properly set to staging hostname?) or the real exception should be displayed to the user, not silently ignored.

**Comment by BenSturmfels** [comment]
I've been able to get the preview working under Django 1.8, but not under 1.10, using the exact same settings. Haven't had a chance to investigate.

**Comment by BenSturmfels** [comment]
Hi @emorozov, sorry to be a pain, but could you please add some details about closing this issue?

**Comment by SalahAdDin** [comment]
@emorozov, i want to know the same.

**Comment by SalahAdDin** [comment]
@emorozov, i want to know the same.

**Comment by emorozov** [comment]
@BenSturmfels @SalahAdDin The problem only occurs when wagtail site hostname mismatches the real hostname. You need to check if you have the site hostname set correctly in the Django admin.

**Comment by BenSturmfels** [comment]
@emorozov glad you were able to resolve your issue, but if configuring the hostname incorrectly results in the somewhat baffling ``'WSGIRequest' object has no attribute 'user'``, I think we need a better solution. Otherwise this is going to cause a headache for a lot of people unnecessarily.

**Comment by emorozov** [comment]
@BenSturmfels then the proper solution would be one of the following:

* ignore middleware errors during processing dummy wagtail request
* remove common middleware from the list of middleware when processing dummy request
* do not use middleware at all when processing fake request

Like I said in the initial message this whole dummy request thing for preview feels like a crutch. I have a feeling that it can be made in a more robust and elegant manner, but I'm not really sure I can do it.

**Comment by abadger1406** [comment]
(nw) dave@big5:/home/nw$ tail -f logs/uwsgi.log 
  File "/home/Env/nw/lib/python3.6/site-packages/wagtail/core/models.py", line 1324, in serve_preview
    return self.serve(request)
  File "/home/Env/nw/lib/python3.6/site-packages/wagtail/contrib/forms/models.py", line 237, in serve
    form = self.get_form(page=self, user=request.user)
AttributeError: 'WSGIRequest' object has no attribute 'user'

**Comment by gasman** [comment]
@abadger1406 That one's a bit puzzling - `request.user` would be missing if something failed during the middleware stage, but in that case I can't see how it would proceed to the form page model's `serve` method. Can you post the complete traceback, please?

**Comment by jayden2** [comment]
After upgrading to 2.2.2 from 2.0 I have noticed this on production only:

> AttributeError
> 'WSGIRequest' object has no attribute 'site'

An odd thing I've also noticed is if I change the sites port to say 200, and then refresh the preview page the page loads. Then on subsequent loads the above error happens.

**Comment by Chukwunonso** [comment]
Had this problem while upgrading to Django 2.1.7 and Wagtail 2.4 from 1.10.3 and 1.13 respectively. 
Seemed none of the middleware was being triggered including the `wagtail.core.middleware.SiteMiddleware` which should set the `site` attribute to the `request` object. The issue went away when I changed the middleware setting from 
```
MIDDLEWARE_CLASSES = (...)
```
to
```
MIDDLEWARE = (...)
```

**Comment by gasman** [comment]
See #5427 for a full diagnosis and (hopefully) fix.

**Comment by CVYY39** [comment]
Quick fix for my site was to add localhost to the ALLOWED_HOSTS string. Worked like a charm.

**Comment by tobyspark** [comment]
I had the same symptoms. I added Wagtail 2.9 to an existing Django 2.2 site, following the [documentation](https://docs.wagtail.io/en/stable/getting_started/integrating_into_django.html). Everything worked, except for page previews in production, which resulted in 400 Bad Request error. 

I’ve read through the various issues linked in #5427 and am none the wiser, given a) the fixes already incorporated to Wagtail 2.9 and e.g. I have none of the middleware installed, and no _Wagtail site_ settings beyond `WAGTAIL_SITE_NAME`.

Adding `localhost` to the production ALLOWED_HOSTS results in the previews working. But clearly is a bodge. Posting as FYI; this is a fairly vanilla site, I’m surprised by this.

**Comment by gasman** [comment]
@tobyspark It sounds like you don't have the correct site hostname set under Settings -> Sites in the Wagtail admin.

Having said that, the intention behind Wagtail's site configuration is that for _single-site_ installations, the out-of-the box setup should continue to work for as long as possible even if the hostname hasn't been filled in - so, for example, the `{% pageurl %}` tag doesn't include the domain part of the URL. If the only thing standing in the way of a fully-functional site in DEBUG=False mode is the mismatch between the hostname used for previewing and ALLOWED_HOSTS, then we should fix that - I think that could be done by:

* in `make_preview_request`, see if the intended hostname for the request is allowed by ALLOWED_HOSTS
* if not, see if the Wagtail site configuration consists of a single Site record with `is_default_site=True` (i.e. this Wagtail installation treats all hostnames as equivalent)
* if so, use the first item in ALLOWED_HOSTS in place of whatever the Site record's hostname says

**Comment by tobyspark** [comment]
@gasman Correct, and a slight mea-culpa in that I didn’t find those settings I was using Wagtail when logged-in as an editor not administrator. 

Nonetheless, there’s no mention that setting the site name is required in the _Integrating Wagtail into a Django project_ documentation – and, generally, yes your intention is correct and taking the first item in ALLOWED_HOSTS seems a better approach than forcing that parameter to be set.

**Comment by SebCorbin** [comment]
> @tobyspark It sounds like you don't have the correct site hostname set under Settings -> Sites in the Wagtail admin.
> 
> Having said that, the intention behind Wagtail's site configuration is that for _single-site_ installations, the out-of-the box setup should continue to work for as long as possible even if the hostname hasn't been filled in - so, for example, the `{% pageurl %}` tag doesn't include the domain part of the URL. If the only thing standing in the way of a fully-functional site in DEBUG=False mode is the mismatch between the hostname used for previewing and ALLOWED_HOSTS, then we should fix that - I think that could be done by:
> 
>     * in `make_preview_request`, see if the intended hostname for the request is allowed by ALLOWED_HOSTS
> 
>     * if not, see if the Wagtail site configuration consists of a single Site record with `is_default_site=True` (i.e. this Wagtail installation treats all hostnames as equivalent)
> 
>     * if so, use the first item in ALLOWED_HOSTS in place of whatever the Site record's hostname says

This won't work for wildcards in ALLOWED_HOSTS

**Comment by gasman** [comment]
@SebCorbin That's easily fixed - for `*` wildcards we're already covered by the first step, and for `.example.com` we just strip off the leading dot.

**Comment by henriquelalves** [comment]
I was also having this problem. My "ALLOWED_HOSTS" had no wildcards, only the hostname of the website, and I couldn't preview any page on Wagtail admin view. I'm using Caddy instead of Nginx.

What fixed it for me was changing the port of the Wagtail site config to "443" instead of the default "80". My Django application is redirecting SSL and had all SECURE_HSTS options, so maybe that was crashing the preview when using an "http" port.
