### ISSUE TITLE
AttributeError: type object 'HomePage' has no attribute 'landing'

### ISSUE THREAD

**Issue by Ibrokola** [wagtail/wagtail#3463]
This was migrating properly 2 days ago, suddenly it started showing me this errors. Kindly find the related link codes and the homepage codes after the error... I am working with Django 1.10.6 and wagtail 1.9

File "manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ibrokola/Desktop/NewIbro/my_env/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/ibrokola/Desktop/NewIbro/my_env/lib/python3.5/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ibrokola/Desktop/NewIbro/my_env/lib/python3.5/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ibrokola/Desktop/NewIbro/my_env/lib/python3.5/site-packages/django/core/management/base.py", line 342, in execute
    self.check()
  File "/home/ibrokola/Desktop/NewIbro/my_env/lib/python3.5/site-packages/django/core/management/base.py", line 374, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/ibrokola/Desktop/NewIbro/my_env/lib/python3.5/site-packages/django/core/management/commands/migrate.py", line 62, in _run_checks
    issues.extend(super(Command, self)._run_checks(**kwargs))
  File "/home/ibrokola/Desktop/NewIbro/my_env/lib/python3.5/site-packages/django/core/management/base.py", line 361, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/ibrokola/Desktop/NewIbro/my_env/lib/python3.5/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/ibrokola/Desktop/NewIbro/my_env/lib/python3.5/site-packages/wagtail/wagtailadmin/checks.py", line 64, in get_form_class_check
    edit_handler = cls.get_edit_handler()
  File "/home/ibrokola/Desktop/NewIbro/my_env/lib/python3.5/site-packages/wagtail/utils/decorators.py", line 55, in __call__
    return self.value
  File "/home/ibrokola/Desktop/NewIbro/my_env/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/ibrokola/Desktop/NewIbro/my_env/lib/python3.5/site-packages/wagtail/utils/decorators.py", line 51, in value
    return self.fn(self.cls)
  File "/home/ibrokola/Desktop/NewIbro/my_env/lib/python3.5/site-packages/wagtail/wagtailadmin/edit_handlers.py", line 824, in get_edit_handler
    return EditHandler.bind_to_model(cls)
  File "/home/ibrokola/Desktop/NewIbro/my_env/lib/python3.5/site-packages/wagtail/wagtailadmin/edit_handlers.py", line 334, in bind_to_model
    'children': [child.bind_to_model(model) for child in self.children],
  File "/home/ibrokola/Desktop/NewIbro/my_env/lib/python3.5/site-packages/wagtail/wagtailadmin/edit_handlers.py", line 334, in <listcomp>
    'children': [child.bind_to_model(model) for child in self.children],
  File "/home/ibrokola/Desktop/NewIbro/my_env/lib/python3.5/site-packages/wagtail/wagtailadmin/edit_handlers.py", line 354, in bind_to_model
    'children': [child.bind_to_model(model) for child in self.children],
  File "/home/ibrokola/Desktop/NewIbro/my_env/lib/python3.5/site-packages/wagtail/wagtailadmin/edit_handlers.py", line 354, in <listcomp>
    'children': [child.bind_to_model(model) for child in self.children],
  File "/home/ibrokola/Desktop/NewIbro/my_env/lib/python3.5/site-packages/wagtail/wagtailadmin/edit_handlers.py", line 752, in bind_to_model
    related = getattr(model, self.relation_name).rel
AttributeError: type object 'HomePage' has no attribute 'landing'

class RelatedLink(LinkFields):
    title = models.CharField(max_length=255)

    panels = [
        FieldPanel('title'),
        MultiFieldPanel(LinkFields.panels, "Link"),
    ]

    class Meta:
        abstract = True

class HomePageLanding(Orderable, RelatedLink):
    page = ParentalKey('ibro.HomePage', related_name='landing')
    colour = models.CharField(max_length=255)
    background = models.ForeignKey(
        'wagtailimages.Image',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='+'
    )
    logo = models.ForeignKey(
        'wagtailimages.Image',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='+'
    )
    text = models.CharField(
        max_length=255
    )

    panels = RelatedLink.panels + [
        ImageChooserPanel('background'),
        ImageChooserPanel('logo'),
        FieldPanel('colour'),
        FieldPanel('text'),
    ]

class HomePageSupports(Orderable, RelatedLink):
    page = ParentalKey('ibro.HomePage', related_name='supports')
    image = models.ForeignKey(
        'wagtailimages.Image',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='+'
    )

    panels = RelatedLink.panels + [
        ImageChooserPanel('image')
    ]

class HomePage(Page):
    hero_intro_primary = models.TextField(blank=True)
    hero_intro_secondary = models.TextField(blank=True)
    intro_body = RichTextField(blank=True)
    work_title = models.TextField(blank=True)
    blog_title = models.TextField(blank=True)
    clients_title = models.TextField(blank=True)

    class Meta:
        verbose_name = "Homepage"

    content_panels = [
        FieldPanel('title', classname="full title"),
        MultiFieldPanel(
            [
                FieldPanel('landing_intro_primary'),
                FieldPanel('landing_intro_secondary'),
            ],
            heading="Landing intro"
        ),
        InlinePanel('landing', label="Landing"),
        FieldPanel('intro_body'),
        FieldPanel('socialmedia_title'),
        FieldPanel('blog_title'),
        FieldPanel('supports_title'),
        InlinePanel('supports', label="Supports"),
]

**Comment by Ibrokola** [comment]
Can someone please point what I am doing wrong to me, as error seems to emanate from model attribute binding in edit_handlers

**Comment by gasman** [comment]
Hi @Ibrokola,
Github is the wrong forum for support requests - they should go on Stack Overflow.

Please don't create duplicate issues - it won't get you an answer any faster (the Wagtail core team already follow 'wagtail'-tagged questions on Stack Overflow) and it just means we have to waste time cleaning up the issues list.

If you update one of your questions on Stack Overflow to include all the necessary information including code and error message, in a readable format (please use Stack Overflow's preview feature), and delete the duplicate question, then I'll be happy to take a look - I can't promise anything, though.
