### ISSUE TITLE
Can't add RichTextField to custom User Account Settings form

### ISSUE THREAD

**Issue by juan0tron** [wagtail/wagtail#5961]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

I am creating a custom User model for my Wagtail site. I'd like to add a rich text editor to my users' bios under the Account Settings menu. However, adding `bio = RichTextField()` to my user model causes my server to stop with this error (full stack trace at the bottom of this ticket):

```
  File "/.virtualenvs/env/lib/python3.6/site-packages/wagtail/users/views/users.py", line 15, in <module>
    from wagtail.users.forms import UserCreationForm, UserEditForm
ImportError: cannot import name 'UserCreationForm'
```

### Steps to Reproduce

Following the docs on creating a [Custom User Model](https://docs.wagtail.io/en/v2.8.1/advanced_topics/customisation/custom_user_models.html), create a user model with the field "bio" as a RichTextField and add the model to your Wagtail settings:

```
# /users/models.py

from django.contrib.auth.models import AbstractUser
from django.db import models

from wagtail.core.fields import RichTextField

class User(AbstractUser):
	# bio = models.TextField(max_length=600, blank=True) # This works, but the field will show in the form as a standard HTML textarea
	bio = RichTextField(max_length=600, blank=True) # This causes the server to crash with an error
```

```
# settings/base.py
...
# ===== Custom User Model =====
AUTH_USER_MODEL = 'users.User'
WAGTAIL_USER_CUSTOM_FIELDS = ['bio']
...
```

### Additional Files

I'm using a wagtail hook to put this form in the Account Settings panel and not in the "Edit User" form. However, I get the above error even if I put the field in the CustomUserEditForm and CustomUserCreationForm recommended in the Wagtail Docs. Posting these anyway in case they help.

```
# /users/forms.py 

from django import forms
from django.utils.translation import ugettext_lazy as _

from users.models import User

from wagtail.admin.forms import WagtailAdminModelForm

class AuthorBioForm(WagtailAdminModelForm): # Using Django's forms.ModelForm will give the same result 
	bio = RichTextField()

	class Meta:
		model = User
		fields = ("bio",)
```

```
# /users/wagtail_hooks.py

from django.conf.urls import include, url
from django.utils.translation import ugettext_lazy as _
from django.urls import reverse

from users.views import change_bio

from wagtail.core import hooks

@hooks.register('register_admin_urls')
def register_admin_urls():
	return [
		url(r'^account/bio/$', change_bio, name='wagtailadmin_custom_account_change_bio'),
	]

@hooks.register('register_account_menu_item')
def register_account_change_bio(request):
	return {
		'url': reverse('wagtailadmin_custom_account_change_bio'),
		'label': _('Change bio'),
		'help_text': _('Update your author bio.'),
	}
```

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

I am not sure if this is a bug or it is intended, but it is unclear the best way to go about this. The end result I want is a rich text editor in my Account Settings form. 

Should I have `bio = RichTextField()` in my model and `bio = RichTextField()` in my form?

OR, should I have `bio = models.TextField()` in my model and `bio = RichTextField()` in my form, and add something to my form that loads the Rich Text Editor widget / JS? 

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (yes / no)

Yes.

### Technical details

* Python version: 3.6.8
* Django version: 3.0
* Wagtail version: 2.8.1
* Browser version: Firefox 68

### Full error log:

```
(env) my-wagtail-project$ ./manage.py ruerver

Watching for file changes with StatReloader
Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/.virtualenvs/env/lib/python3.6/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/.virtualenvs/env/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    self.check(display_num_errors=True)
  File "/.virtualenvs/env/lib/python3.6/site-packages/django/core/management/base.py", line 395, in check
    include_deployment_checks=include_deployment_checks,
  File "/.virtualenvs/env/lib/python3.6/site-packages/django/core/management/base.py", line 382, in _run_checks
    return checks.run_checks(**kwargs)
  File "/.virtualenvs/env/lib/python3.6/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/.virtualenvs/env/lib/python3.6/site-packages/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "/.virtualenvs/env/lib/python3.6/site-packages/django/core/checks/urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "/.virtualenvs/env/lib/python3.6/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/.virtualenvs/env/lib/python3.6/site-packages/django/urls/resolvers.py", line 587, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/.virtualenvs/env/lib/python3.6/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/.virtualenvs/env/lib/python3.6/site-packages/django/urls/resolvers.py", line 580, in urlconf_module
    return import_module(self.urlconf_name)
  File "/.virtualenvs/env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/my-wagtail-project/myapp/urls.py", line 6, in <module>
    from wagtail.admin import urls as wagtailadmin_urls
  File "/.virtualenvs/env/lib/python3.6/site-packages/wagtail/admin/urls/__init__.py", line 13, in <module>
    from wagtail.admin.urls import password_reset as wagtailadmin_password_reset_urls
  File "/.virtualenvs/env/lib/python3.6/site-packages/wagtail/admin/urls/password_reset.py", line 3, in <module>
    from wagtail.admin.views import account
  File "/.virtualenvs/env/lib/python3.6/site-packages/wagtail/admin/views/account.py", line 15, in <module>
    from wagtail.users.forms import (
  File "/.virtualenvs/env/lib/python3.6/site-packages/wagtail/users/forms.py", line 179, in <module>
    class UserCreationForm(UserForm):
  File "/.virtualenvs/env/lib/python3.6/site-packages/django/forms/models.py", line 257, in __new__
    apply_limit_choices_to=False,
  File "/.virtualenvs/env/lib/python3.6/site-packages/django/forms/models.py", line 174, in fields_for_model
    formfield = f.formfield(**kwargs)
  File "/.virtualenvs/env/lib/python3.6/site-packages/wagtail/core/fields.py", line 18, in formfield
    defaults = {'widget': get_rich_text_editor_widget(self.editor, features=self.features)}
  File "/.virtualenvs/env/lib/python3.6/site-packages/wagtail/admin/rich_text/__init__.py", line 37, in get_rich_text_editor_widget
    return cls(**kwargs)
  File "/.virtualenvs/env/lib/python3.6/site-packages/wagtail/admin/rich_text/editors/draftail/__init__.py", line 31, in __init__
    self.features = feature_registry.get_default_features()
  File "/.virtualenvs/env/lib/python3.6/site-packages/wagtail/core/rich_text/feature_registry.py", line 49, in get_default_features
    self._scan_for_features()
  File "/.virtualenvs/env/lib/python3.6/site-packages/wagtail/core/rich_text/feature_registry.py", line 54, in _scan_for_features
    for fn in hooks.get_hooks('register_rich_text_features'):
  File "/.virtualenvs/env/lib/python3.6/site-packages/wagtail/core/hooks.py", line 47, in get_hooks
    search_for_hooks()
  File "/.virtualenvs/env/lib/python3.6/site-packages/wagtail/core/hooks.py", line 41, in search_for_hooks
    list(get_app_submodules('wagtail_hooks'))
  File "/.virtualenvs/env/lib/python3.6/site-packages/wagtail/utils/apps.py", line 23, in get_app_submodules
    yield name, import_module('%s.%s' % (name, submodule_name))
  File "/.virtualenvs/env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/my-wagtail-project/users/wagtail_hooks.py", line 5, in <module>
    from users.views import change_bio
  File "/my-wagtail-project/users/views.py", line 6, in <module>
    from users.forms import AuthorBioForm
  File "/my-wagtail-project/users/forms.py", line 11, in <module>
    class AuthorBioForm(WagtailAdminModelForm):
  File "/.virtualenvs/env/lib/python3.6/site-packages/wagtail/admin/forms/models.py", line 66, in __new__
    new_class = super(WagtailAdminModelFormMetaclass, cls).__new__(cls, name, bases, attrs)
  File "/.virtualenvs/env/lib/python3.6/site-packages/modelcluster/forms.py", line 234, in __new__
    new_class = super(ClusterFormMetaclass, cls).__new__(cls, name, bases, attrs)
  File "/.virtualenvs/env/lib/python3.6/site-packages/django/forms/models.py", line 257, in __new__
    apply_limit_choices_to=False,
  File "/.virtualenvs/env/lib/python3.6/site-packages/django/forms/models.py", line 178, in fields_for_model
    formfield = formfield_callback(f, **kwargs)
  File "/.virtualenvs/env/lib/python3.6/site-packages/wagtail/admin/forms/models.py", line 47, in formfield_for_dbfield
    return db_field.formfield(**kwargs)
  File "/.virtualenvs/env/lib/python3.6/site-packages/wagtail/core/fields.py", line 18, in formfield
    defaults = {'widget': get_rich_text_editor_widget(self.editor, features=self.features)}
  File "/.virtualenvs/env/lib/python3.6/site-packages/wagtail/admin/rich_text/__init__.py", line 37, in get_rich_text_editor_widget
    return cls(**kwargs)
  File "/.virtualenvs/env/lib/python3.6/site-packages/wagtail/admin/rich_text/editors/draftail/__init__.py", line 31, in __init__
    self.features = feature_registry.get_default_features()
  File "/.virtualenvs/env/lib/python3.6/site-packages/wagtail/core/rich_text/feature_registry.py", line 49, in get_default_features
    self._scan_for_features()
  File "/.virtualenvs/env/lib/python3.6/site-packages/wagtail/core/rich_text/feature_registry.py", line 54, in _scan_for_features
    for fn in hooks.get_hooks('register_rich_text_features'):
  File "/.virtualenvs/env/lib/python3.6/site-packages/wagtail/core/hooks.py", line 47, in get_hooks
    search_for_hooks()
  File "/.virtualenvs/env/lib/python3.6/site-packages/wagtail/core/hooks.py", line 41, in search_for_hooks
    list(get_app_submodules('wagtail_hooks'))
  File "/.virtualenvs/env/lib/python3.6/site-packages/wagtail/utils/apps.py", line 23, in get_app_submodules
    yield name, import_module('%s.%s' % (name, submodule_name))
  File "/.virtualenvs/env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/.virtualenvs/env/lib/python3.6/site-packages/wagtail/users/wagtail_hooks.py", line 11, in <module>
    from wagtail.users.urls import users
  File "/.virtualenvs/env/lib/python3.6/site-packages/wagtail/users/urls/users.py", line 3, in <module>
    from wagtail.users.views import users
  File "/.virtualenvs/env/lib/python3.6/site-packages/wagtail/users/views/users.py", line 15, in <module>
    from wagtail.users.forms import UserCreationForm, UserEditForm
ImportError: cannot import name 'UserCreationForm'
```

**Comment by laymonage** [comment]
I think this may have been fixed by #7050, using the `register_account_settings_panel` hook.

With the following code:

```py
# models.py
from django.db import models

from django.contrib.auth.models import AbstractUser
from wagtail.fields import RichTextField


class User(AbstractUser):
    country = models.CharField(verbose_name="country", max_length=255)
    bio = RichTextField()
```

```py
# forms.py
from django import forms
from django.contrib.auth import get_user_model

User = get_user_model()


class UserCountryBioForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["country", "bio"]
```

```py
# wagtail_hooks.py
from wagtail.admin.views.account import BaseSettingsPanel
from wagtail import hooks
from .forms import UserCountryBioForm


@hooks.register("register_account_settings_panel")
class CountryBioSettingsPanel(BaseSettingsPanel):
    name = "country-bio"
    title = "Country and Bio"
    order = 500
    form_class = UserCountryBioForm
    form_object = "user"
```

I was able to get it working on Wagtail 6.1.3:

<img width="1018" alt="the country field and the bio rich text field showing up in the account settings" src="https://github.com/user-attachments/assets/b9176b37-d5db-48ee-a749-14e8b431c0d5">

Though I noticed a different issue, and have filed a separate one for it: #12184.
