### ISSUE TITLE
TypeError: required_fields() missing 1 required positional argument: 'self'

### ISSUE THREAD

**Issue by snj** [wagtail/wagtail#4345]
### Issue Summary

When I migrated wagtail version from 1.13 to 2.0, got this error:

```
Traceback (most recent call last):
File "manage.py", line 9, in <module>
  execute_from_command_line(sys.argv)
File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
  utility.execute()
File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 356, in execute
  self.fetch_command(subcommand).run_from_argv(self.argv)
File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 283, in run_from_argv
  self.execute(*args, **cmd_options)
File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 330, in execute
  output = self.handle(*args, **options)
File "/usr/local/lib/python3.5/dist-packages/django_extensions/management/utils.py", line 59, in inner
  ret = func(self, *args, **kwargs)
File "/usr/local/lib/python3.5/dist-packages/django_extensions/management/commands/runserver_plus.py", line 258, in handle
  self.inner_run(options)
File "/usr/local/lib/python3.5/dist-packages/django_extensions/management/commands/runserver_plus.py", line 297, in inner_run
  self.check(display_num_errors=self.show_startup_messages)
File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 359, in check
  include_deployment_checks=include_deployment_checks,
File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 346, in _run_checks
  return checks.run_checks(**kwargs)
File "/usr/local/lib/python3.5/dist-packages/django/core/checks/registry.py", line 81, in run_checks
  new_errors = check(app_configs=app_configs)
File "/usr/local/lib/python3.5/dist-packages/wagtail/admin/checks.py", line 63, in get_form_class_check
  if not issubclass(edit_handler.get_form_class(), WagtailAdminPageForm):
File "/usr/local/lib/python3.5/dist-packages/wagtail/admin/edit_handlers.py", line 336, in get_form_class
  fields=self.required_fields(),
File "/usr/local/lib/python3.5/dist-packages/wagtail/admin/edit_handlers.py", line 261, in required_fields
  fields.extend(handler.required_fields())
File "/usr/local/lib/python3.5/dist-packages/wagtail/admin/edit_handlers.py", line 261, in required_fields
  fields.extend(handler.required_fields())
TypeError: required_fields() missing 1 required positional argument: 'self'
```

### Steps to Reproduce

1. migrated wagtail version from 1.13 to 2.0
2. python3 manage.py runserver

### Technical details

* Python version: 3.5
* Django version: 1.11.11
* Wagtail version: 2.0

**Comment by snj** [comment]
I traced the error with pdb and found that the handler was EmbedVideoChooserPanel.

https://github.com/infoportugal/wagtail-embedvideos/blob/master/wagtail_embed_videos/edit_handlers.py#L15

**Comment by snj** [comment]
The problem was fixed.

**Comment by SalahAdDin** [comment]
@snj Please see my fork, is updated and more complete.
